language: php

php:
  - 5.4

before_script:
  - composer install --prefer-dist
  - app/yiic environment dev
  - php -S localhost:31415 -t web/ &

script: vendor/bin/codecept run

branches:
  only:
    - master