language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --prefer-dist
  - chmod +x app/yiic
  - app/yiic permissions
  - app/yiic environment change dev
  - app/yiic migrate --interactive=0
  - php -S localhost:31415 -t www/ &

branches:
  only:
    - master